### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by stone-shrine** [stone-shrine/protospace-38890#1]
# URL
https://protospace-38890.onrender.com

**Comment by shodai-ito** [comment]
@stone-shrine さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
### **`コメント機能`**
- [x] **フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
空のフォームを投稿すると、エラー画面になってしまいます。

### **`ユーザー詳細機能`**
- [x] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
ユーザー名が一部未編集です。
<img width="802" alt="スクリーンショット 2023-01-30 9 10 54" src="https://user-images.githubusercontent.com/62537107/215364437-50f4d361-e0d3-47a6-a26c-f3d10e9921b5.png">

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by stone-shrine** [comment]
コメント機能のエラーとユーザー詳細の表示を修正しました。
ご確認お願いします。

**Comment by ghost** [comment]
@stone-shrine さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、続けて修正していただきたい箇所がございました。
以下のご確認をお願いします！

**[修正依頼箇所]**

**ユーザー管理機能**
- [ ] **ユーザーの新規登録ができるようにしましょう**
現在、ユーザーの新規登録ができなくなっている状態です。
情報を正しく入力したらユーザーの新規登録ができるように修正をお願い致します。


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
挙動確認を行い、修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
　https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by stone-shrine** [comment]
自分でも確認しましたが、問題無く新規登録できました。
データベースの中身を全て削除してみたので、再度ご確認お願いします。

**Comment by motomuun** [comment]
@stone-shrine さん、再度ご提出頂きありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
